// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        "board-row": string;
        game: string;
        "game-board": string;
        "game-info": string;
        "kbd-navigation": string;
        square: string;
        status: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
